[package]
name = "windowproject"
version = "0.1.0"
edition = "2024"

[dependencies]
# gl_bindings = { git = "https://github.com/Zephyros1938/gl_bindings.git" }
gl = "0.14.0"
glfw = "0.59.0"
log = "0.4.27"
log4rs = "1.3.0"
stb_image = "0.3.0"
